/// Shared Store ID validation/normalization.
///
/// Store IDs are UUIDs generated by Supabase. This helper also removes
/// invisible Unicode characters and normalizes common Unicode dash characters
/// so IDs copied from dashboards/documents are validated consistently.
class StoreIdValidator {
  static const _invisible = <int>{
    0x200B, // zero-width space
    0x200C, // zero-width non-joiner
    0x200D, // zero-width joiner
    0x2060, // word joiner
    0xFEFF, // zero-width no-break space / BOM
  };

  static const _dashCharacters = <int>{
    0x2010, // hyphen
    0x2011, // non-breaking hyphen
    0x2012, // figure dash
    0x2013, // en dash
    0x2014, // em dash
    0x2212, // minus sign
  };

  static String normalize(String value) {
    final buffer = StringBuffer();

    for (final rune in value.runes) {
      if (_invisible.contains(rune)) {
        continue;
      }
      if (_dashCharacters.contains(rune)) {
        buffer.write('-');
      } else {
        buffer.writeCharCode(rune);
      }
    }

    return buffer.toString().trim();
  }

  static bool isValid(String value) {
    final normalized = normalize(value);
    final uuidPattern = RegExp(
      r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-'
      r'[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    );
    return uuidPattern.hasMatch(normalized);
  }
}
